### ISSUE TITLE
Broken URLs

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew#40392]
I ran `brew fetch --build-from-source` on all formulae and found the following issues:

- [x] `burp` (404) #40393
- [x] `colortail` (domain down) #40428
- [x] `daq` (404) #40430
- [x] `davix` (repo not found) #40432
- [x] `ffmpeg2theora` (SHA1 error on patch) #40757
- [x] `fits` (404) #40434
- [x] `fuseki` (404) https://github.com/Homebrew/homebrew/commit/66fdc20fa724c793f8bd71d2d7d168465581d951
- [x] `gant` (404) https://github.com/Gant/Gant/issues/3, #43326
- [x] `hh` (404) #40757
- [x] `httpry` (network is unreachable) #40757
- [x] `libopendkim` (404) #40757
- [x] `libtar` (SHA1 error) #40757
- [x] `libtomcrypt` (domain down) #40757
- [x] `libtommath` (domain down) #40757
- [x] `libtorrent` (timeout) #40460
- [x] `logentries` (SHA1 error) #41562
- [x] `luvit` (404) #42525
- [x] `makepkg` (domain down) #41562
- [x] `mitmproxy` (404)
- [x] `mpssh` (404 on patch) #40390
- [x] `openrtsp` (404) #41562
- [x] `openwsman` (SHA256 error) #41562
- [x] `owamp` (404 on patch) (I sent an email to the patch author on 2015/07/12) #43361
- [x] `par2tbb` (SHA256 error then domain down) #43360
- [x] `pdftoipe` (404) #40528
- [x] `qi` (404) #41366
- [x] `redo` (SHA1 error) [no error as of 2015/08/27]
- [x] `rocket` (SHA1 error) #41364
- [x] `rtorrent` (timeout) #40489
- [x] `sdelta3` (domain down) #40436
- [x] `sfk` (SHA256 error) #41562
- [x] `snort` (404) #40461
- [x] `ssldump` (404) #41297
- [x] `tcsh` (ftp 550) #40462
- [x] `uni2ascii` (SHA256 error) #40466
- [x] `unison` (SHA1 error) #40711

I checked four times each one of these, plus checked from another server (different ISP, different city) for the checksum errors.
[See the detailed output in this gist](https://gist.github.com/bfontaine/65b25faa1b793ff9e54f).

Last update: 2015/08/28.

**Comment by xu-cheng** [comment]
:+1: Good work.

**Comment by mikemcquaid** [comment]
General policy for this stuff: bump if there's a newer version available and otherwise find if they've moved somewhere else or just boneyard if the project is dead. Thanks!

**Comment by bfontaine** [comment]
> General policy for this stuff: bump if there's a newer version available and otherwise find if they've moved somewhere else or just boneyard if the project is dead. Thanks!

Great, that’s what I had in mind.

**Comment by DomT4** [comment]
`libtorrent`'s website suffered a take over apparently - https://github.com/rakshasa/rtorrent/issues/295#issuecomment-104705086, but is currently down and has been since early April. Switched the homepage/url in #40460.

`snort` is only outdated - They seem to yank old versions off the server after a couple of subsequent releases. I've bumped it in #40461.

**Comment by bfontaine** [comment]
The `sfk` checksum issue seems to be due to upstream changing their tarballs:

```
NOTE: HEAD VERSION - ALL FILES MAY CHANGE WITHOUT NOTICE!
      This is the head version of SFK, and bug fixes will lead
      to a replacement of all files given here without previous
      notice. If you use SFK in your project, and it is important
      for you that files do not change, take an older version
      of SFK that does not contain this notice.
```

**Comment by bfontaine** [comment]
Seems like `redo` already had some SHA1 issues in the past: 378937ce

**Comment by apjanke** [comment]
`daq` is 404 again; new update at #42401
