### ISSUE TITLE
Broken homepages

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew#41610]
I fetched all homepages in the core; here are the problematic ones, each with the corresponding `curl` error. This inspired #41607.

- [x] `bibtexconv`: failed to connect to host (#41611)
- [x] `bip`: peer certificate cannot be authenticated with known CA certificates (self-signed cert)
- [x] ~~`cf`: failed to connect to host~~
- [x] ~~`clang-format`: couldn't resolve host. The given remote host was not resolved~~
- [x] `ddar`: failed to connect to host (#43358)
- [x] ~~`fastbit`: failed to connect to host~~
- [x] `fcgiwrap`: peer certificate cannot be authenticated with known CA certificates
- [x] `freealut`: couldn't resolve host. The given remote host was not resolved
- [x] `gd`: peer certificate cannot be authenticated with known CA certificates
- [x] `iat`: couldn't resolve host. The given remote host was not resolved
- [x] `konoha`: couldn't resolve host. The given remote host was not resolved
- [x] ~~`l-smash`: couldn't resolve host. The given remote host was not resolved~~
- [x] `libmowgli`: failed to connect to host
- [x] `libwbxml`: failed to connect to host
- [x] `luciddb`: couldn't resolve host. The given remote host was not resolved
- [x] `man2html`: failed to connect to host
- [ ] `minbif`: peer certificate cannot be authenticated with known CA certificates
- [x] `mksh`: peer certificate cannot be authenticated with known CA certificates
- [x] ~~`paq8px`: failed to connect to host~~
- [x] `par2tbb`: couldn't resolve host. The given remote host was not resolved
- [x] `pax-construct`: failed to connect to host
- [x] `phantomjs`: failed to connect to host (#41623)
- [x] ~~`qd`: failed to connect to host~~
- [x] `recode`: failed to connect to host
- [x] `tcptrack`: couldn't resolve host. The given remote host was not resolved
- [ ] `trafshow`: failed to connect to host
- [x] `txt2man`: failed to connect to host (#41624)

**Comment by apjanke** [comment]
Some of these are back up now and might have been transient errors:

cf
clang-format
fastbit
l-smash
paq8px
qd

**Comment by bfontaine** [comment]
Thank you @apjanke, I updated the list.

**Comment by Moisan** [comment]
`par2tbb` has been [moved to graveyard](https://github.com/Homebrew/homebrew/pull/43360) so it shouldn't be in this list.

**Comment by bfontaine** [comment]
Thanks @Moisan I updated it.

**Comment by DomT4** [comment]
`minbif` seems to be working fine again now, and shoved `trafshow` onto an archive page in https://github.com/Homebrew/homebrew/pull/50449. Will keep an eye on the bottle stats; if they aren't significant going forwards we may want to just boneyard the formula. Think that resolves this list :smiley:.
