### ISSUE TITLE
Missing conflicts

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew#42766]
One unexpected thing that the binaries list from [command-not-found](https://github.com/Homebrew/homebrew-command-not-found) lets us do is to check for conflicts between formulae.

I took the list and grouped together core formulae providing the same binary. I then removed the conflicts that were already declared, and here are those which are missing:

- [x] `aardvark_shell_utils`, `coreutils` (`realpath`) #42767
- [x] ~~`berkeley-db4`, `berkeley-db` (`db_archive`, `db_checkpoint`, `db_deadlock`, `db_dump`, `db_hotbackup`, `db_load`, `db_printlog`, `db_recover`, `db_stat`, `db_upgrade`, `db_verify`, `db_checkpoint`, `db_deadlock`, `db_dump`, `db_hotbackup`, `db_load`, `db_printlog`, `db_recover`, `db_stat`, `db_upgrade`, `db_verify`)~~ (the former is keg-only)
- [x] `byobu`, `ctail` (`ctail`) #42768
- [x] `camlistore`, `hello` (`hello`)
- [x] `ccat`, `ccrypt` (`ccat`)
- [x] `crush-tools`, `num-utils` (`range`)
- [x] `cspice`, `libftdi0`, `openhmd` (`simple`) #44849
- [x] `cspice`, `enscript` (`states`) #45051
- [x] `cspice`, `fondu` (`tobin`) #45290
- [x] `eet`, `efl` (`eet`)
- [x] `elixir-build`, `narwhal` (`json`)
- [x] `es`, `kes` (`es`)
- [x] ~~`etcd`, `etcdctl` (`etcdctl`)~~ see #37508
- [x] `flvstreamer`, `rtmpdump` (`rtmpsrv`, `rtmpsuck`, `rtmpsuck`) #45419
- [x] `freeling`, `hunspell` (`analyze`) #45590
- [x] ~~`fsw`, `fswatch` (`fswatch-run`, `fswatch-run-bash`, `fswatch-run-zsh`, `fswatch-run-bash`, `fswatch-run-zsh`)~~
- [x] `gnu-cobol`, `open-cobol` (`cob-config`, `cobc`, `cobcrun`, `cobc`, `cobcrun`)
- [x] `groovy`, `groovysdk` (`grape`, `groovy`, `groovyc`, `groovyConsole`, `groovydoc`, `groovysh`, `java2groovy`, `startGroovy`, `groovy`, `groovyc`, `groovyConsole`, `groovydoc`, `groovysh`, `java2groovy`, `startGroovy`)
- [x] `ipmiutil`, `renameutils` (`icmd`)
- [x] `irods`, `renameutils` (`icp`, `imv`, `imv`)
- [x] `jena`, `samba` (`tdbbackup`, `tdbdump`, `tdbdump`)
- [x] ~~`jpeg-turbo`, `mozjpeg` (`tjbench`)~~ (the latter is `keg_only`)
- [x] `lha`, `lhasa` (`lha`)
- [x] `libevent`, `pincaster` (`event_rpcgen.py`)
- [x] `libzzip`, `zuf`, `zzuf` (`zzcat`)
- [x] `mariadb`, `mytop` (`mytop`)
- [x] `mecab-ko`, `mecab` (`mecab`, `mecab-config`, `mecab-config`)
- [x] `multirust`, `rust` (`cargo`, `rust-lldb`, `rustc`, `rustdoc`, `rust-lldb`, `rustc`, `rustdoc`)
- [x] ~~`nss`, `resty` (`pp`)~~ (the former is `keg_only`)
- [x] `nut`, `rhino` (`rhino`)
- [x] `par`, `rancid` (`par`) #42770
- [x] `pssh`, `putty` (`pscp`) #42771
- [x] `storm`, `stormssh` (`storm`)

Each line shows the conflicting binaries between parentheses.

**Comment by DomT4** [comment]
Oh, your PolarSSL entry is out of date. Sorry, I should have caught that and submitted it to your command-not-found. `md5sum`, `sha1sum` and such are no longer shipped by `polarssl`. They've all been compressed into `crypt_and_hash`.

**Comment by bfontaine** [comment]
Thanks @DomT4, I updated the list. I also forgot to check for keg-only formulae, so the `berkeley-db4`/`berkeley-db` conflict is out because the former is keg-only.

**Comment by bfontaine** [comment]
The `mecab` issue here might be broader than that, see https://github.com/Homebrew/homebrew/issues/41501#issuecomment-126634120

As @xu-cheng suggested, we should maybe include all `mecab-*` formulae as optional resources in the `mecab` formula.

**Comment by Moisan** [comment]
[`etcdctl` formula has been stripped](https://github.com/Homebrew/homebrew/pull/37508) so it shouldn't be in this list.

**Comment by bfontaine** [comment]
Thanks @Moisan; I had an outdated `etcdctl` entry: https://github.com/Homebrew/homebrew-command-not-found/commit/3ae3dd4a72874d99e447070851af2752f17996f2
