### ISSUE TITLE
Formula renames bug [Tracking]

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew#42965]
* [x] Link problem **critical bug** #42857
* [x] Better update output #42801
* [x] `--force` should bypass tap origin check #42801
* [x] Migration and any other operations which manipulate keg(old or new) (e.g. uninstall) should lock keg. **critical bug** #43025
* [x] `Formulary#to_rack` should follow the symlink. f857815178885c7c82127d0b0a9f4639d0b2e035
* [x] Old opt_link should be handled for `brew switch/(un)link/upgrade`. **critical bug** #42998
* [ ] Performance issue for `brew update` and potentially other brew commands. We can use `brew prof`(available from `brew tap homebrew/dev-tools`) to do some analysis.
* [x] The variable names inside `migrator.rb` should have uniform naming style. For example, `foo_bar` vs `foobar`. All the variables and methods would better to have proper document as comment. Variable names should reflect their purpose, e.g.:
  * We should use `new_cellar` instead of `new_path`.
  * We should use `old_linked_keg` instead of `old_keg`.
  * We should make variables named after `xxx_keg` a `Keg` object rather than `Pathname` object.
  * We should avoid variable name as `keg`, which is confusing as we don't know it's old or new.
* [x] Possible bugs regarding migration advice for `install/outdated`. https://github.com/Homebrew/homebrew/pull/42940#discussion_r37194059 https://github.com/Homebrew/homebrew/pull/42940#discussion_r37194427
* [x] If renamed formula has new DSL, `brew update` can crash.  #43353

**Comment by xu-cheng** [comment]
cc @mikemcquaid @vladshablinsky

**Comment by xu-cheng** [comment]
I suggest to fix each problem per PR.

**Comment by vladshablinsky** [comment]
>  Old opt_link should be handled for brew switch/(un)link/upgrade. **critical bug**

Ho do we implement it? There was a little discussion about that.

* I tried to get `oldname` using `INSTALL_RECEIPT` and loading the formula, but we decided, that it wasn't the best idea.

* You suggested to get `oldname` from the symlinks to the new name keg in `opt`.
  * We are able to do this after the migration occurs if `oldname` was optlinked.
  * If there is a link in opt pointing to some of `newname`'s keg and the name of that link is not `newname`, then we can say, that `oldname` is a name of that link.

According to approach you suggested, we don't need to remove `Migrator#link_oldname_opt` and `Migrator#unlink_oldname_opt`. What we need is to 

I would implemented it this way:
```ruby
def oldname_opt_record
  @oldname_opt_record ||= if (opt_dir = HOMEBREW_PREFIX/"opt").directory?
    opt_dir.subdirs.detect do |dir|
      # Check if both opt and self are the kegs from the same package.
      dir.symlink? && dir != opt_record && path.parent == dir.resolved_path.parent
    end
  end
end

def remove_oldname_opt_record
  return unless oldname_opt_record
  @oldname_opt_record.unlink
  @oldname_opt_record.parent.rmdir_if_possible
  @oldname_opt_record = nil
end

def optlink(mode = OpenStruct.new)
  opt_record.delete if opt_record.symlink? || opt_record.exist?
  make_relative_symlink(opt_record, path, mode)

  if oldname_opt_record
    oldname_opt_record.delete
    make_relative_symlink(oldname_opt_record, path, mode)
  end
end

def uninstall
  path.rmtree
  path.parent.rmdir_if_possible
  remove_opt_record if optlinked?
  remove_oldname_opt_record
end
```

**Comment by xu-cheng** [comment]
After some thought, I don't think you should fix that in `keg.rb`. Instead, you should handle it inside each commands. The reason is the old opt record is independent to the current keg. Especially when we dealing with multiple kegs installed in the same rack.

**Comment by vladshablinsky** [comment]
I thought we were to make old opt record depend on the current keg. So, we don't do that?

**Comment by xu-cheng** [comment]
We should make old opt record pointed to the same new opt record. But it should not handle inside keg object. For example, in the case of upgrade we unlink old keg then link new keg. But these two kegs are independent as they are different versions. 

I would suggest to create `Keg#optlink_to(target, mode)` method, in which the old opt record should be passing as an argument. We can then add a `Keg#oldname_opt_record` method to try to locate possible oldname opt record based on file system. You should notice that when you call these two methods, the keg objects are different.

**Comment by vladshablinsky** [comment]
Let's suppose `oldname -> newname` and there is only one keg `0.1` at the moment when we perform the migration. We have:
* `opt/newname` points to `Cellar/newname/0.1`
* `opt/oldname` points to `Cellar/newname/0.1`

**upgrade current behaviour**
* `opt/newname` points to `Cellar/newname/0.2`
* `opt/oldname` points to `Cellar/oldname/0.1`

**upgrade expected behaviour**
Let's suppose there is a new version `0.2` after that. We `upgrade newname` and now we have
* `opt/newname` points to `Cellar/newname/0.2`
* :exclamation: `opt/oldname` points to `Cellar/newname/0.2` and should be updated from the state when it pointed to `Cellar/newname/0.1`

If you agree with everything above, then

> For example, in the case of upgrade we unlink old keg then link new keg. But these two kegs are independent as they are different versions.

We unlink old keg means we unlink `0.1` version, then link new  keg means we link `0.2`, right?

`0.1` and `0.2` are independent and in case of `upgrade` it's `formula_installer` which links and optlinks new installed keg. So, If keg could relink its oldname opt, we wouldn't have problems here.

I don't see a problem here. The keg that we link and optlink in `upgrade` and in any other place can just link old name opt the same way it links opt.

> Instead, you should handle it inside each commands. The reason is the old opt record is independent to the current keg. Especially when we dealing with multiple kegs installed in the same rack.

old opt record points to `Cellar/newname/0.1`, but the current keg is `Cellar/newname/0.2`. But why can't we just use that fact when we link that new keg (`0.2`) and relink old name.


If that is not what is expected, then can you please explain what do we want?
Would be great with `oldname` and `newname` for i.e. `upgrade` command, and if you tell where should `opt/oldname` point it would be awesome. However if I described expected behaviour of `upgrade` properly, it's not needed.

I know maybe I spend too much time trying to understand what exactly is needed instead of working on the solution, but I think we don't understand each other.

**Comment by xu-cheng** [comment]
You are right. I think your approach is correct. I overcomplicated the problem in my previous mind. Can you submit a PR to fix this issue and adding more test for this case inside `test_keg.rb`? Thanks.

After this, we should address the keg lock problem.

**Comment by vladshablinsky** [comment]
I haven't opened PR solving lock problem yet, but I have a branch:  https://github.com/Homebrew/homebrew/compare/master...vladshablinsky:lock Is that what you meant, @xu-cheng?

**Comment by vladshablinsky** [comment]
I'm going to work on the stuff that haven't been solved yet at the beginning of the following week.

**Comment by mikemcquaid** [comment]
I think this can get closed now because the only remaining issue is performance. Nice work @vladshablinsky!

**Comment by mikemcquaid** [comment]
@vladshablinsky Would you be interested in working on/working out a solution for being able to use formula's old names for new formulae? Thanks!

**Comment by mikemcquaid** [comment]
@vladshablinsky If not: would you be able to give us some pointers in doing so ourselves? Thanks!

**Comment by vladshablinsky** [comment]
I think I would be interested, but when you want the feature to be implemented? I mean maybe I don't have time to work on it 40 hours per week.

And the solution for the feature is really tricky I think, so I need time for thinking thoroughly again. At the beginning of the summer I wasn't able to come up with something acceptable, that doesn't break Homebrew concepts too much <s>like `ack` package should be stored in `Cellar/ack`. I think I needed to have some storage for the packages and symlink to Cellar only ones that are installed</s>.

So I need to think. I'm happy to help with both giving pointers and implementing the feature by myself, but it needs serious efforts to come up with the solution (at least now I think it does).

**Comment by mikemcquaid** [comment]
@vladshablinsky Unlike Summer of Code: it can take as long as you want. We could have something that requires user-intervention if you e.g. have the existing package installed and want to install a new one. Thanks for replying so quickly :sparkles:

**Comment by vladshablinsky** [comment]
@mikemcquaid I've been thinking a little about the implementation and have came up with something like idea, but I need to think it over. The idea is to have something like a unique timestamp associated with every formula and every entry in `formula_renames`. Now I think it can help a lot in resolving ambiguity while migrating, because we can compare timestamps. By timestamp I mean some value equals to 0 at the beginning and incremented by 1 each time we need to have new timestamp (each timestamp is unique and we don't have two formula with the same timestamp). Let me know if you don't like the 'timestamp idea'. I'm not sure if it solves the problem , but maybe it's a no-no and I'm on the wrong way and need to think of something else.

**Comment by mikemcquaid** [comment]
@vladshablinsky It's an interesting idea, certainly. I was thinking something like having the `old_name` fallback be temporary and be able to identify if there's an `old_name` and a new formula shadowing that name in which case you may need to upgrade/reinstall the `old_name` package so it has the `new_name`, remove the symlink and then install the new package.

**Comment by vladshablinsky** [comment]
>be able to identify if there's an old_name and a new formula shadowing that name

@mikemcquaid I think it can be done if we have that timestamps I told about.

Dependencies also shouldn't be missed here. If something depends on `oldname`, then `oldname` goes to `newname` and new `oldname` is released, we can encounter wrong dependency resolution. However `timestamp idea` can solve this problem. Suppose we have something like this:

 1. `oldname` has `0` stamp. 
 2. `dependent` is a formula, that depends on `oldname`. Let's suppose `dependent` has `1` stamp.
 3. We install `oldname`
 4. then, we rename `oldname` to `newname` and have something like `oldname -> newname, 2` in `formula_renames` and `2` associated with `newname`,
 5. then new `oldname` is released, it has `3` timestamp. Locally we have `oldname` migrated to `newname`. And a formula for new released `oldname`, but we don't have new released `oldname` installed.
 6. What happens when we install `dependent`? We compare timestamp of `oldname` which is 1 and `oldname -> newname, 2`, which is 2 and understand, that `dependent` depends on `newname`, because 1 is less than 2.
 7. OK, next time someone wants to change `dependent` he must update all the dependencies and resolve them to the currently actual names and then update the timestamp for `dependent`. Let's suppose it's done and we didn't do 6th step. Now dependent is the same as it was, ans only timestamp was updated. The timestamp for it is `4`. We install `dependent`, and install `oldname` as its dependency, because 4 is greater than 2 (`oldname -> newname, 2`).

And because there can be lots of PRs pending, it's difficult to get new timestamp locally, so we need CI to make new timestamps and assign them to formulae.

**Comment by mikemcquaid** [comment]
@vladshablinsky I think it's OK to apply restrictions so e.g. nothing can still depend on `oldname` for us to move it to `newname`.

Where do you see these timestamps being stored?

**Comment by vladshablinsky** [comment]
> Where do you see these timestamps being stored?

@mikemcquaid  Hm, storing all of them in one file doesn't seem to be fast. We can have separate file for formulae begin with `a`, `b`, etc. It make things faster, but maybe it's not so elegant solution. There are about 2000 formulae, each file will contain about 100 entries and we will need to rewrite some of the files. Searching is ~20 times faster than if we had all the timestamps in one file though.

**Comment by bfontaine** [comment]
Homebrew/command-not-found has a [5k-lines file](https://github.com/Homebrew/homebrew-command-not-found/blob/master/executables.txt); using `grep` for a rough filter then Ruby for a more precise one works great. I haven’t done any benchmark though.

**Comment by mikemcquaid** [comment]
@vladshablinsky I think we can probably get timestamps from Git logs instead.

**Comment by vladshablinsky** [comment]
@bfontaine thanks, so searching is fast. What if we need to rewrite the whole file?

@mikemcquaid can we be sure that there won't be same timestamps? Can't be the order of commits broken? Git uses system time in commits and we can change the time manually, so can we rely on git logs?

Here you can see the date in the future. :)

```
commit 51be1a80a8dfadfdc3b91e5dc51f16512dd9fc3c
Author: BrewTestBot <brew-test-bot@googlegroups.com>
Date:   Tue Oct 13 03:39:12 2015 +0100

    dbxml: add 6.0.17 bottle.

commit f87cba69171edd654ce4a1318f2514288f5f1201
Author: Cyril Scetbon <cscetbon@gmail.com>
Date:   Tue Jan 27 00:56:05 2015 +0100

    dbxml 6.0.17 (new formula)

    Closes #37299.

    Signed-off-by: Mike McQuaid <mike@mikemcquaid.com>
```

**Comment by bfontaine** [comment]
> What if we need to rewrite the whole file?

In that case I don’t know :no_mouth:

**Comment by mikemcquaid** [comment]
@vladshablinsky You can't rely on time but you can rely on commit ordering.

**Comment by vladshablinsky** [comment]
@mikemcquaid great, it seems that ordering provides all the information we need to resolve everything properly. However, it can be slow to find whether one commit is a descendant of another. It's slower than comparing numbers, but it's already implemented. So, don't you think, that performance can be an issue?

**Comment by mikemcquaid** [comment]
@vladshablinsky I think with Git comparisons like that can be made to be very fast. If necessary we can do some caching of Git operations but I'd be surprised if they are needed.

**Comment by vladshablinsky** [comment]
@mikemcquaid OK, I think I can start working on it in several weeks. I'm going to provide a gist or just a comment here about the implementation details and then if everybody is happy I'll begin working on the feature. Will ask if something is unclear.

**Comment by mikemcquaid** [comment]
@vladshablinsky Sounds great, thanks so much :heart:

**Comment by vladshablinsky** [comment]
@mikemcquaid I collected my thoughts about renames into a [document](https://gist.github.com/vladshablinsky/789ae17f9aa9d42e50b7). It's very raw now and needs improvements, I think. Anyway, I hope some ideas can help and we'll come up with something, not necessarily with the approach described in the document, but we will.

### Here is a duplicate of what is inside the document:


Formula renames: allow any type of renames
==========================================

I suggest you reading this and not going into the details very deeply at first, because several approaches are described here and something can be wrong at some point and then another approach is introduced.
Thanks!

Metadata
========

Let's describe core formula renames at this point and then try to add same functionality to taps.

Let's have the following metadata for formulae:

1. We assign a commit to every installed package. The commit is the last commit applied to formula file (something like `git rev-list -1 origin/master path/to/formula`
2. Every formula has its own file with information about renames for this name. Deletions are also stored in that files.
    Let's take `A` as an example formula. Every entry in this file for `A` renames has structure like this: `commit_i newname_i`. This shows that `A` was renamed to `newname_i` at `commit_i`, where `commit_i` is a `rename_commit~1`
    Let's look at this file for `A`renames closer:

    ```
    # A-renames
    94156b595b96008d47f7b5b37851fd178c9d00a7, A_1
    7f979528dea723c1a1aae4ca31c1689df6df1703, A_2
    f3cf43acfc764acba84fa20b4c42a3e0b5382589, A_3
    b0cfecff16cf8bd04a544f19f69ed363126b3dae, ""  #<--- remove formula after commit
    10c8b45678a446b759677294765a3505ba9b20f5, A_4
    #           \                              /
    #            \                            /
    #             \               new name after that commit
    #              \
    #    commit before rename commit
    ```
    
    What information can we get from this file? We know, that `A` was renamed to `A_1`, then `A` was renamed to `A_2`, which means, that either something was renamed to `A` or new `A` was created before next rename of `A`. Important note here is that entries are sorted in this file. It's the same if we say that we add new entries to the end of file each time. It can guarantee, that commit at line `i` always goes before commit at line `j` if `i < j`.
    
    We suppose that at each moment of time or it's better to say at each commit, we have only one formula with particular name.
    
We have that structure, what's next? Let's suppose we have formula `A` installed at some commit `0000001`, and this commit is an ancestor (not necessarily direct) of `94156b59`, let's get new name of `A` package now. How do we do this? We go to `A-renames` file and try to find the first line, for which the commit will be a descendant of `0000001`. We get the name of `A` -- it is `A_1` at commit `94156b59`. Next thing we do is going to `A_1-renames` file and doing the same procedure (*find the first line, for which the commit will be a descendant of `94156b59`*). We continue this process untill we can't find a descedant or file with renames doesn't exist, which means, that that formula with that name has never been renamed before. So, we can resolve formula at each point of time.

**Note:** Binary search can be used here to *find the first line, for which the commit will be a descendant of `some_commit`*.

**Pitfal:** We probably need a way to control the size of metadata, but currently for tap migrations and formula renames there is no such way and I think it doesn't exist. The summary number of lines in all the renames files is the number of all the renames and deletions of formulae in repository.

Dependency resolution
=====================

```
                                         F ... F*
                                        /
       /-------> A ... A* -----------> D ... D*
      /                                 \
     /                                   G ... G*
    /
   X ----------> B ... B* -------> E ... E*
    \
     \ 
      \
       \-------> C ... C*
```

Let's try to resolve dependencies for `X`. A **very important note here** is that at the moment of the last commit changing `X` it had all the dependencies resolved. It means, that if `X` depends on `A` at `commit_1` and if `A` changes name after `commit_1` we need to find the first rename after `commit_1` in `A-renames` file. Then we find the commit at which `A` changes name and it's `A`'s next name, and continue searching in renames files `A -> A_1 -> A_2 -> ... -> A*` After that we go to the next dependency of `X`, which is `B`, resolve it and get `B*`, then to `C`, and then resolve dependencies of dependeicies. At the end we have our dependencies resolved. If at some point formula is removed, then we can't install package.


brew update and migration process
=================================

Let's difine migration mechanism that we have now at Homebrew as Current Migration Mechanism (CMM)

What can change on `brew update` if speaking about formulae?

* multiple renames (`A -> B -> C`)
* deletions (`A -> ""`)
* new formulae (`A` -> ""`, new `A`)
* loop renames (`A -> B -> A`)

At each moment of time (commit) we have only *ONE* formula with some name and there is only one way to resove every formula.

### first case: suppose everything was clear before the update (no symlinks in the cellar, every installed package has didn't need to be migrated)

```
I    [#] A    \
N    [#] B     |
     [#] C      >  installed and present in report
     [#] D     |
R    [#] E    /
E    [ ] F
P    [ ] G
O    [ ] H
R    [ ] I
T    [ ] J
```

Migrations possible only for the formulae that are installed present in report. Not all of these migrations can be completed successfully.

What should we do to perform migrations:

1. Resolve every name and get last names for each package or find out that package is removed.
2. Find all the conflicting names e.g. `A -> B`, `B -> A`, we can't have them both migrated using CMM, because we can't have
`A` and `B` can't be both directories and symlinks. (At this point I don't solve this problem, I just show, that it can happen, let's say, that `A` and `B` are *BROKEN*, and later introduce *FIX* operation and show how we can handle this situation).
3. For all packages without conflicts we can use CMM.

### second case: some of the packages have wrong names: i.e. they didn't migrate at some update before and need to be *FIX*ed. Some symlinks can present in the cellar, which means that some migrations were made in the past.


We have some packages installed in the cellar and we have report. Let's look only on those pacakges, that are installed and present in report. There can be some broken packages that are not in report, but we don't handle this case at this point.

Let's suppose `A` failed to migrate at some point. `A -> X` is in report and `A` is installed, it can be not the same `A` as installed. Suppose `A` failed to migrate to `B`, so in `A-renames` we have at least `some_commit, B`. Let's try to resolve formula for out installed `A` packaged. For that purpose we have `commit_installed_A` associated with every installed package, so we try to find in `A-renames` first commit that is after `commit_installed_A`. Then we continue resolving the formula as we did it before (looking through renames files), at the end of the procedure we have some name `A*`. We do the same procedure for all the formula that are installed and present in report.
Some cases possible here:

* `A -> X` -- `A` has nothing to do with installed `A`, installed `A` was renamed at some point and then new `A` appeared and it's new `A` that is renamed to `X` in the last update.
* `A -> ... -> A` package probably need to be updated but it don't need to migrate it.

Basically we do almost the same as in the first step. We migrate only those packages that we can. We can migrate package that was migrated before if there is no conflicts. E.g. `A -> B` and we have `A` linked to `B` in the cellar. At the last update we have `B -> C`. After rename we'll have `B` linked to `C` and `A` linked to `C`.

**Pitfall:** What if `A -> B` migration failed, then we were able to install `B`, so we had `A` and `B` installed, and `A` moved to `B`, but we didn't perform migrations for `A` -- if we try to resolve formula for installed `A` and `B`, it will be the same package. `A` is broken, `B` is not.

FIX operation
=============

Let's suppose we have a broken package. What does it mean?
The package is broken, if formula for installed package `A` is not `A`. (Package can be removed or renamed, but still present in the cellar).

If package is broken, we can't just migrate it using CMM. What if we remove this package and reinstall it with new name? Something that depends on it can be broken, so, we need to reinstall it as well (by the way, the software that depends on the package we're reinstalling can also be renamed). What we do here is reinstall all the packages in the dependency tree starting from leaves, for example, if we need to fix `X`:


```
                                  <--- F
                                 /
       <-------- A <----------- D 
      /                          \
     /                            <--- G
    /
   X <---------- B <------- E
    \
     \ 
      \
       \<------- C
```

We find every formula that depends on `X`. We can see, that `A`, `B` and `C` depend on `X`. A note here: something can dapend on `X` if `something_commit < X_commit`, where `something_commit` is commit of last change to the formula and `X` commit is a commit assigned to a package when it was installed. We do the same procedure for `A`, `B`, `C`. At the end we have leaves `F`, `G`, `E`, `C`. We can sort this tree topoligically and reinstall every package in that order. For our example it would be `F, G, D, A, E, B, C, X`. We reinstall every formula from this list moving from left to right and at the end of this process we have `F, G, D, A, E, B, C, X` fixed. 

**Note:** If `Y` is not broken, then fix for this package doesn't change it and fixes only formula that depends on `Y`.

### Deletions 
If something is deleted, we don't break the software that depends on it, but the package, that is deleted is broken and need to be **FIX**ed. 

### Pitfal:
We have `X` installed. It's broken, and was renamed to `Y` at some point. If `X` is broken it means, that for some reason we can't migrate it using CMM. What if we're able to install `Y` without fixing `X`? We have two same packages, but `A` haven't been migrated yet. We need to handle this case too.

Alternative approach
====================

What if we have Cellar and Storage. Cellar has only symlinks to Storage and Storage store packages.
For example we have `A` and `B` installed.
Different packages have different names in Storage, even package that had name `X` at some point is stored not in the same directory as the package that has name `X` now.

```
Cellar               Storage
    A ---------------> A_abacaba
    
    B ---------------> B_0101001
```

If we rename `A` to `B`, after rename we have

```
Cellar               Storage
    A ------\          A_abacaba
             \
    B         \------> B_0101001
```

If there is no links to something in the Storage, it means that they can't appear in future, because if new `A` appears, in storage it will be with new suffix like `A_131232`.

Pros: easy migrations, easy deletions.
Cons: major change of the structure.

To think
========

* How to test
* Taps
* Some other edge cases

**Comment by mikemcquaid** [comment]
@vladshablinsky Thanks for the thinking about this and the long explanation! I think the `A-renames` approach could work but I think it could probably be done without a file but just from querying the Git log. I'm happy to help you more there as my Git knowledge is pretty decent (I wrote a book about it :wink:).

I think it's OK for e.g. `brew update` to refuse to run and prompt the user to manually run `brew migrate` if that's necessary. Otherwise the (first) general approach sounds good to me :+1:

**Comment by vladshablinsky** [comment]
@mikemcquaid we could have it without metadata If we could track renames just using git, but I'm not sure we can do this, we can just guess and compare lines in two files.

I think we can be almost sure about renames when we rename file using `git mv`, then commit, and after that we change the formula name inside that file. In this case we can handle renames just using git and two commits for formula rename. And if we take one particular commit it can happen that formula name is not the same as file name.

So the metadata I described is about tracking names of particular formula, not just about the fact that something present at particular moment of time. If we want to use git, we probably need to change renaming process to something similar to `git mv` with two commits. What do you think here? Am I wrong?

By the way, I read your book in September, it was cool, I liked it, especially the part with workflows!

**Comment by mikemcquaid** [comment]
Thanks for the kind words @vladshablinsky! I still think we can track the renaming using Git but if we can't we can always use a file.

**Comment by vladshablinsky** [comment]
@mikemcquaid Sorry for the delay in my comments. I'm going to work on the first case, then. (With manual renaming and cleaning the Cellar if conflicts appear).
I'll think about more edge cases and will ask you for the help with git, when it's needed.

**Comment by mikemcquaid** [comment]
@vladshablinsky No rush!

**Comment by mikemcquaid** [comment]
@vladshablinsky Also let me know if you want me iMessage or anything for questions.
